//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechProjectHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryMaster
    {
        public int Enq_Id { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string MobNo { get; set; }
        public string Query { get; set; }
        public Nullable<System.DateTime> Enq_DT { get; set; }
    }
}
