//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechProjectHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackMaster
    {
        public int Fid { get; set; }
        public string Feedback_Title { get; set; }
        public string Feedback_Detail { get; set; }
        public string DeveloperId { get; set; }
        public Nullable<System.DateTime> MsgDT { get; set; }
    
        public virtual DeveloperMaster DeveloperMaster { get; set; }
    }
}
