//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechProjectHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostProjectMaster
    {
        public int Project_Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Proj_Description { get; set; }
        public string Filename { get; set; }
        public Nullable<System.DateTime> Upload_DT { get; set; }
    }
}
