//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechProjectHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskMaster
    {
        public int Task_Id { get; set; }
        public string ForDeveloper { get; set; }
        public Nullable<System.DateTime> ForDate { get; set; }
        public string TaskTitle { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public string TaskFile { get; set; }
    
        public virtual DeveloperMaster DeveloperMaster { get; set; }
    }
}
