//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechProjectHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkReportMaster
    {
        public int Report_Id { get; set; }
        public string Report_Title { get; set; }
        public string Report_Descrip { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<bool> IsHelpNeeded { get; set; }
        public string Submitted_By { get; set; }
        public Nullable<System.DateTime> Submitted_DT { get; set; }
    
        public virtual DeveloperMaster DeveloperMaster { get; set; }
    }
}
